// eslint-disable-next-line no-shadow
export enum SlavicLanguage {
  Belarusian = 'be',
  Bosnian = 'bs',
  Bulgarian = 'bg',
  Croatian = 'hr',
  Czech = 'cs',
  Kashubian = 'csb',
  LowerSorbian = 'dsb',
  Macedonian = 'mk',
  Montenegrin = 'cnr',
  ChurchSlavonic = 'cu',
  OldRussian = 'orv',
  Polabian = 'pox',
  Polish = 'pl',
  Russian = 'ru',
  Rusyn = 'rue',
  Serbian = 'sr',
  LowerSilesian = 'sli',
  Slovak = 'sk',
  Slovenian = 'sl',
  Ukrainian = 'uk',
  UpperSorbian = 'hsb',
}
